# Site settings
title: Unstructured
email: samedhi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A journal of what I am working on and thinking about. I provide here
  links to every project I work upon. I also periodically review things,
  and sometimes, if you are good, give my opinion. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samedhi.github.io" # the base hostname & protocol for your site
twitter_username: samedhi
github_username:  samedhi
stackoverflow_id: 21317
stackoverflow_username: stephen-cagle

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

kramdown:
  input: GFM
